create table roles (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    
INSERT INTO roles (id, name) VALUES (1,  'ADMIN');
INSERT INTO roles (id,  name) VALUES (2,  'USER');

    
    